[package]
authors = ["powturbo <powturbo [AT] gmail [DOT] com>"]
build = "build.rs"
name = "Turbo-Base64"
version = "0.60.0"

[dependencies]
rand = "0.8"

[build-dependencies]
bindgen = "*"
cmake = "0.1"
